language: node_js
node_js:
  - "stable"
env:
  - PORT=8000 DATABASE=test
jobs:
  include:
  - stage: test-react-app
    before_install:
    - cd react-app
    install:
    - npm install
    cache:
      directories:
        - "node_modules"
    script:
    - echo "Run react-app testing"
    - npm run build

  - stage: test-express-app
    before_install:
    - cd express-app
    install:
    - npm install
    cache:
      directories:
        - "node_modules"
    script:
    - echo "Run express-app testing"
    - npm run test

  - stage: deploy-to-heroku
    script:
    - npm run build
    - cd express-app
    before_deploy:
    - grep -vwE "^build$" .gitignore > .gitignore.build
    - mv .gitignore.build .gitignore
    - rm .gitignore.build
    deploy:
      skip_cleanup: true
      provider: heroku
      edge: true
      app: rctech-owl
      api_key: $HEROKU_API_KEY
      on:
        all_branches: true
        # condition: $TRAVIS_BRANCH =~ ^(master|testing)$

  - stage: test-heroku
    script: curl https://rctech-owl.herokuapp.com/
