language: node_js
node_js: lts/*
env:
  global:
  - secure: QxdYUsnRrJ5taree41Wis/MTkcuaFE+zVTFktBAO4HCll2O512DVNm6CzKSKFRZaAq+d5nSK3ZjZw6Fv1t8D2FnzVr6ZOGYKZFriGvB/lCTbBjlzCgQuX12GG2HC+6BD7maVIkQCovPIJr0heIgGFsexa8vu2pD/2XOykK8RsYkxC5299gEO5SjPJyx3gLSbRSkj2VeHW/3SWIOPSOS++6IHOojnVg3bUFeP07klBAQRuCT4vT/r/m6RKnawWNp2N3ybttduSKH+TPRQfh6edMFnGpL916Bis9PM0kHVMxU6bIBavpWpgjOM3G5r/X8dCbORamKhldjj8VsKTr80byJ/mvCIG4xXRh9Yyd8pk4iAfdMCleSd4qbaiZ/tJeKPp/LI99FhY3lRbvcCxG6emETRFQEfRUlk0kkHdR6TsaOAF7C63ksLcPeEGg47L7gads22ydsYrd04e0EcdN9YOpwSWSXx0TOGbLJNqZgZLoByaIb1Y3Cavg8VCGdNatcKC6K0XDQIJ+k1hDkVdwRcGtHJBFbHjE94rptyhiS+BYYjeGeTd/OEpmH8mku5hC8yzRyqr0gjX1bXqyk4r8K1ydtSOchH4XHd4LadWAqh5PV8HYnapGDRfQTuKlSSINjjidRmcuE7IZ4nZKj75LtTBJNgrtCMb4wbPh1vpbEg2Ek=
  - secure: Hszz4RrWNcOyk6Kg/yyw09APhpKWONQNM/ZfB2gjQl//Mz3LzbL9xV2JiAKC/hdh2tl8w+LWcAQaBg/1tov69VcnJtU0MiJoUsL2iW5in9ghemAQqE7ZpZEIq9ceWPmV+dTmf5KEF54OYfD9xFD+8oL3a3FFK7OONFq53g/9EO1Frp/dDs2+rw2IgaVIgam8cd2MMHAJNvT9Ucaek0lN3uP7bt4YZAVpjpXfuj16GiLBn3qx83bx8HnHP3bLrLQQYf6uYvM0q26qHlswoufsrJsGggJjWxa2BdTU2ub0TJTzd/ryYrn1m//FNwN0+YYSSoPGT0yJmbVcFih/VjeRB4RUFcT4jsn0HkfydMUhKwHctZbL5sHCnLSjqK0PSe1qGYmsYddCDwbD5TF2UVsTZzQJDJyUq67UGzHO/TMBBLMWbFy/98q7G4Z4ez+aFef4TF3nsdFcmMeK/5lSLsfP0/lX5KVrTIDhybZ+cu7AMSLProK4dvQfQos+kZJezzPVrrv14NDdn9vnLyhJsAxvO0bpjLQI8hzNNslO0qzRhP0ae+VUZkeYeUSnnt+I02CZzhlL88RbEoaCKe1pLix2vmfO4UI3n4Z5JHesMjiCHP7KjOkubgNSzivdOaly9tdgVAjzT0ygr6G8a3cdIM1pqVtaQAlbXhpk8GKSRVM/2eY=
  matrix:
  # - DATABASE=habos
  - DATABASE=test
jobs:
  include:
  - stage: express-app tests
    before_install:
    - cd express-app
    install:
    - npm install
    script:
    - echo "Run express-app testing"
    - npm run start
  - stage: deploy to heroku
    script: skip
    pre-deploy:
    - cd express-app
    deploy:
      provider: heroku
      edge: true
      app: hall-booking-system
      api_key:
        secure: Zpi0SV/T4suF5x+YUYf8+r9/muj860M4sEXFTzQlla4GxJtM9epJ/1MMApKYSbV8nhCWIS6uHKkweGEaRjaRjt/1nUEMqTp3wy3hilc8h6ve+97tz0+3F0wQo46FUo78p+rDHWpGPxCdwHerrGsm5faTKM/z9nLfeMhCFqTIoKWBPemeh8WsPpGOypsfcjmgM89TIjuEapFi9iUpNwG9LrC7TpzRSaGEhs8vrgj1yDEBon2L8di8h8CfXR/jiLXXq88lzFhlNQDi75Zw61Pbynf8U0q+uQo9YK6sqsEsGn7DA0SBi0Ys+LzwtOWIGYjkaDWaCJUU+B0BlITJ6tosqvcA943599mBzGia9m6HHsv8Mgc7aN/D3RMByo2efi1pD/avdNby+aOtoofBaPxEpYnBNFWH8/9bgnaocMJregAclCCFsgkEW0MgY+lyubRafgrpcLAoZE5GlmJtlf2umd4CCQl/ZhyocAwG/zHM8D468jxOTgoY5WBqoYxSj0ynR9ascjZym/nlXoZHn9CsphJPlqVtmVFAyg8HgcCcOTgAS8lABxPu06GGUfvT6dETWsQoQreycMjYUaiwAkpmXm203Iel+QpqElucCN+iD0TXRurZFXt/Lbzo18IroxvIczEAa7s6ye47fbBwzgyefcAexdkXixUXMQovRvIq8XE=
  - stage: heroku tests
    script: curl https://hall-booking-system.herokuapp.com/
